spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: passpsql
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    schemas: public
    enabled: true
#    locations: classpath:db/migration
#    url: jdbc:postgresql://localhost:5432/postgres
#    password: passpsql
#    user: postgres
